// File: src/lib/quickSendParser.ts
import { ResourceCategory, ResourceFormData } from '../types/resource';
import { autoCategorizeUrl, suggestTitleFromUrl } from './autoCategorize';

export interface ParsedQuickSendResult {
  formData: ResourceFormData;
  extractedUrl: string;
  sourceType: 'direct_url' | 'embedded_url' | 'text_note';
  isAutoGenerated: boolean;
}

/**
 * Sanitizes arbitrary input string by removing null characters,
 * invisible control codes, and truncating excessive length to prevent ReDoS.
 */
function sanitizeRawInput(input: unknown): string {
  if (typeof input !== 'string') {
    if (input === null || input === undefined) return '';
    try {
      return String(input);
    } catch {
      return '';
    }
  }

  // Strip null bytes and control characters (preserving newlines and tabs)
  const cleaned = input.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '');
  // Cap at 10,000 characters to avoid memory DOS
  return cleaned.slice(0, 10000);
}

/**
 * Generates a fail-safe fallback Note resource when parsing errors occur.
 */
function createFallbackNote(text: string): ParsedQuickSendResult {
  const sanitized = sanitizeRawInput(text).trim();
  const noteId = Date.now().toString(36);
  const noteUrl = `https://smart-resource.local/notes/${noteId}`;

  const firstLine = sanitized.split('\n')[0]?.trim() || 'Quick Note';
  const title = firstLine.length > 60 ? `${firstLine.slice(0, 57)}...` : firstLine;
  const description = sanitized || 'Captured note';

  return {
    formData: {
      url: noteUrl,
      title: title || 'Quick Note',
      category: 'Document',
      description,
      tags: ['note', 'quick-send'],
    },
    extractedUrl: noteUrl,
    sourceType: 'text_note',
    isAutoGenerated: true,
  };
}

/**
 * Extracts the first valid HTTP/HTTPS or domain-like URL from a string.
 * Defensively wrapped to prevent regex failures on complex multi-line text blocks.
 */
export function extractUrlFromText(text: unknown): string | null {
  try {
    const sanitized = sanitizeRawInput(text).trim();
    if (!sanitized) return null;

    // 1. Check if the string itself is directly a valid HTTP/HTTPS URL
    if (/^https?:\/\/[^\s]+$/i.test(sanitized)) {
      return sanitized;
    }

    // 2. Search for explicit http:// or https:// inside the text
    const explicitMatch = sanitized.match(/https?:\/\/[^\s<>"{}|\\^`[\]]+/i);
    if (explicitMatch && explicitMatch[0]) {
      return explicitMatch[0].replace(/[.,;:!?)]+$/, '');
    }

    // 3. Search for known domain patterns (e.g. github.com/..., youtu.be/...)
    const domainMatch = sanitized.match(
      /\b((?:[a-zA-Z0-9-]+\.)+(?:com|org|net|io|dev|edu|gov|app|co|ai|me|so|to|be|tech|design|xyz|info))\b[^\s<>"{}|\\^`[\]]*/i
    );
    if (domainMatch && domainMatch[0]) {
      const raw = domainMatch[0].replace(/[.,;:!?)]+$/, '');
      return `https://${raw}`;
    }

    return null;
  } catch (err) {
    console.warn('extractUrlFromText defensive catch:', err);
    return null;
  }
}

/**
 * Extracts hashtags (e.g. #react #dev) from input text.
 */
export function extractHashtags(text: unknown): string[] {
  try {
    const sanitized = sanitizeRawInput(text);
    const matches = sanitized.match(/#([a-zA-Z0-9_\-]+)/g);
    if (!matches) return [];
    return matches
      .map((tag) => tag.replace('#', '').toLowerCase().trim())
      .filter(Boolean);
  } catch {
    return [];
  }
}

/**
 * Parses any incoming input (URL, multi-line text, note, or share payload)
 * and safely transforms it into a structured ResourceFormData object.
 */
export function parseQuickSendInput(rawInput: unknown): ParsedQuickSendResult {
  try {
    const sanitized = sanitizeRawInput(rawInput).trim();
    if (!sanitized) {
      return createFallbackNote('Untitled Note');
    }

    const hashtags = extractHashtags(sanitized);

    // Strip hashtags from plain text
    const cleanedText = sanitized
      .replace(/#([a-zA-Z0-9_\-]+)/g, '')
      .replace(/[ \t]+/g, ' ')
      .trim();

    const extractedUrl = extractUrlFromText(sanitized);

    if (extractedUrl) {
      const category: ResourceCategory = autoCategorizeUrl(extractedUrl);
      const suggestedTitle = suggestTitleFromUrl(extractedUrl);

      // Extract surrounding text excluding the URL
      const textWithoutUrl = cleanedText
        .replace(extractedUrl, '')
        .replace(/https?:\/\/[^\s]+/gi, '')
        .trim();

      let finalTitle = suggestedTitle || 'Web Resource';
      let finalDescription = '';

      if (textWithoutUrl) {
        if (textWithoutUrl.length <= 60 && !textWithoutUrl.includes('\n')) {
          finalTitle = textWithoutUrl;
          finalDescription = `Source: ${extractedUrl}`;
        } else {
          const firstLine = textWithoutUrl.split(/[\n.]/)[0]?.trim() || '';
          if (firstLine && firstLine.length <= 60) {
            finalTitle = firstLine;
            finalDescription = textWithoutUrl;
          } else {
            finalDescription = textWithoutUrl;
          }
        }
      } else {
        try {
          finalDescription = `Referenced from ${new URL(extractedUrl).hostname}`;
        } catch {
          finalDescription = `Referenced URL: ${extractedUrl}`;
        }
      }

      // Generate tags
      const autoTags = new Set<string>(hashtags);
      autoTags.add(category.toLowerCase());

      try {
        const hostname = new URL(extractedUrl).hostname.replace(/^www\./, '');
        const domainName = hostname.split('.')[0];
        if (domainName && domainName.length > 2 && domainName !== 'com') {
          autoTags.add(domainName.toLowerCase());
        }
      } catch {
        // ignore
      }

      return {
        formData: {
          url: extractedUrl,
          title: finalTitle,
          category,
          description: finalDescription,
          tags: Array.from(autoTags).slice(0, 5),
        },
        extractedUrl,
        sourceType: cleanedText === extractedUrl ? 'direct_url' : 'embedded_url',
        isAutoGenerated: true,
      };
    }

    // Default to a plain text note if no URL was found
    return createFallbackNote(cleanedText);
  } catch (err) {
    console.error('parseQuickSendInput recovered from failure:', err);
    return createFallbackNote(typeof rawInput === 'string' ? rawInput : 'Quick Note');
  }
}
