import { ResourceCategory, ResourceFormData } from '../types/resource';
import { autoCategorizeUrl, suggestTitleFromUrl, validateUrl } from './autoCategorize';

export interface ParsedQuickSendResult {
  formData: ResourceFormData;
  extractedUrl: string;
  sourceType: 'direct_url' | 'embedded_url' | 'text_note';
  isAutoGenerated: boolean;
}

/**
 * Extracts the first valid HTTP/HTTPS or domain-like URL from a string.
 */
export function extractUrlFromText(text: string): string | null {
  const trimmed = text.trim();
  if (!trimmed) return null;

  // 1. Check if the string itself is a valid URL
  if (/^https?:\/\/[^\s]+$/i.test(trimmed)) {
    return trimmed;
  }

  // 2. Search for explicit http:// or https:// inside the text
  const explicitMatch = trimmed.match(/https?:\/\/[^\s<>"{}|\\^`[\]]+/i);
  if (explicitMatch) {
    return explicitMatch[0].replace(/[.,;:!?)]+$/, ''); // clean trailing punctuation
  }

  // 3. Search for common domain patterns like github.com/..., youtu.be/..., etc.
  const domainMatch = trimmed.match(
    /\b((?:[a-zA-Z0-9-]+\.)+(?:com|org|net|io|dev|edu|gov|app|co|ai|me|so|to|be|tech|design|xyz|info))\b[^\s<>"{}|\\^`[\]]*/i
  );
  if (domainMatch) {
    const raw = domainMatch[0].replace(/[.,;:!?)]+$/, '');
    return `https://${raw}`;
  }

  return null;
}

/**
 * Extracts hashtags (e.g. #react #dev) from input text.
 */
export function extractHashtags(text: string): string[] {
  const matches = text.match(/#([a-zA-Z0-9_\-]+)/g);
  if (!matches) return [];
  return matches
    .map((tag) => tag.replace('#', '').toLowerCase().trim())
    .filter(Boolean);
}

/**
 * Parses any incoming input (URL, message, note, code snippet) and transforms it
 * into a structured ResourceFormData object ready for instant saving into Firestore.
 */
export function parseQuickSendInput(rawInput: string): ParsedQuickSendResult {
  const input = rawInput.trim();
  const hashtags = extractHashtags(input);

  // Strip hashtags from plain text to leave clean description/title
  const cleanedText = input
    .replace(/#([a-zA-Z0-9_\-]+)/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  const extractedUrl = extractUrlFromText(input);

  if (extractedUrl) {
    const category: ResourceCategory = autoCategorizeUrl(extractedUrl);
    const suggestedTitle = suggestTitleFromUrl(extractedUrl);

    // Extract surrounding text (excluding the URL itself)
    const textWithoutUrl = cleanedText
      .replace(extractedUrl, '')
      .replace(/https?:\/\/[^\s]+/gi, '')
      .trim();

    let finalTitle = suggestedTitle || 'Quick Saved Resource';
    let finalDescription = '';

    if (textWithoutUrl) {
      if (textWithoutUrl.length <= 60 && !textWithoutUrl.includes('.')) {
        finalTitle = textWithoutUrl;
        finalDescription = `Source: ${extractedUrl}`;
      } else {
        // Use first sentence or up to 60 chars as title if sensible
        const firstSentence = textWithoutUrl.split(/[.\n]/)[0].trim();
        if (firstSentence && firstSentence.length <= 60) {
          finalTitle = firstSentence;
          finalDescription = textWithoutUrl;
        } else {
          finalDescription = textWithoutUrl;
        }
      }
    } else {
      finalDescription = `Quick saved from: ${new URL(extractedUrl).hostname}`;
    }

    // Generate smart tags from category and domain
    const autoTags = new Set<string>(hashtags);
    autoTags.add(category.toLowerCase());

    try {
      const hostname = new URL(extractedUrl).hostname.replace(/^www\./, '');
      const domainName = hostname.split('.')[0];
      if (domainName && domainName.length > 2 && domainName !== 'com') {
        autoTags.add(domainName.toLowerCase());
      }
    } catch {
      // ignore
    }

    return {
      formData: {
        url: extractedUrl,
        title: finalTitle,
        category,
        description: finalDescription,
        tags: Array.from(autoTags).slice(0, 5),
      },
      extractedUrl,
      sourceType: cleanedText === extractedUrl ? 'direct_url' : 'embedded_url',
      isAutoGenerated: true,
    };
  }

  // Fallback: Plain text note or snippet with no URL
  // We provide a secure internal reference URL so it satisfies the strict http/https URL requirement
  const noteId = Date.now().toString(36);
  const noteUrl = `https://smart-resource.local/notes/${noteId}`;
  
  const lines = cleanedText.split('\n').map((l) => l.trim()).filter(Boolean);
  const firstLine = lines[0] || 'Quick Note';
  const title = firstLine.length > 50 ? `${firstLine.substring(0, 47)}...` : firstLine;
  const description = lines.length > 1 ? lines.slice(1).join('\n') : cleanedText;

  const noteTags = new Set<string>(hashtags);
  noteTags.add('note');
  noteTags.add('quick-send');

  return {
    formData: {
      url: noteUrl,
      title: title || 'Quick Note',
      category: 'Document',
      description: description || 'Saved via Quick Send',
      tags: Array.from(noteTags).slice(0, 5),
    },
    extractedUrl: noteUrl,
    sourceType: 'text_note',
    isAutoGenerated: true,
  };
}
